version: "3.7"
services:
  api:
    depends_on:
      - db
    ports:
      - "80:8000"
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      NODE_ENV: development
  db:
    image: mongo:latest
    environment:
      config: ./db/mongod.yml
    volumes:
      - type: bind
        source: ./db
        target: /data
