// flow-typed signature: a8a486d2e82a1e1dcc30f5a308f4953c
// flow-typed version: <<STUB>>/postcss-modules-values-replace_v^2.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules-values-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules-values-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-modules-values-replace/index' {
  declare module.exports: $Exports<'postcss-modules-values-replace'>;
}
declare module 'postcss-modules-values-replace/index.js' {
  declare module.exports: $Exports<'postcss-modules-values-replace'>;
}
