// flow-typed signature: 6ea3e00345522ab72ef9731b695dcb28
// flow-typed version: <<STUB>>/react-social-icons_v^2.8.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-social-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-social-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-social-icons/lib/_networks-db' {
  declare module.exports: any;
}

declare module 'react-social-icons/lib/background' {
  declare module.exports: any;
}

declare module 'react-social-icons/lib/icon' {
  declare module.exports: any;
}

declare module 'react-social-icons/lib/mask' {
  declare module.exports: any;
}

declare module 'react-social-icons/lib/networks' {
  declare module.exports: any;
}

declare module 'react-social-icons/lib/react-social-icons' {
  declare module.exports: any;
}

declare module 'react-social-icons/lib/social-icon' {
  declare module.exports: any;
}

declare module 'react-social-icons/lib/social-icons' {
  declare module.exports: any;
}

declare module 'react-social-icons/lib/styles' {
  declare module.exports: any;
}

declare module 'react-social-icons/lib/symbols' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-social-icons/lib/_networks-db.js' {
  declare module.exports: $Exports<'react-social-icons/lib/_networks-db'>;
}
declare module 'react-social-icons/lib/background.js' {
  declare module.exports: $Exports<'react-social-icons/lib/background'>;
}
declare module 'react-social-icons/lib/icon.js' {
  declare module.exports: $Exports<'react-social-icons/lib/icon'>;
}
declare module 'react-social-icons/lib/mask.js' {
  declare module.exports: $Exports<'react-social-icons/lib/mask'>;
}
declare module 'react-social-icons/lib/networks.js' {
  declare module.exports: $Exports<'react-social-icons/lib/networks'>;
}
declare module 'react-social-icons/lib/react-social-icons.js' {
  declare module.exports: $Exports<'react-social-icons/lib/react-social-icons'>;
}
declare module 'react-social-icons/lib/social-icon.js' {
  declare module.exports: $Exports<'react-social-icons/lib/social-icon'>;
}
declare module 'react-social-icons/lib/social-icons.js' {
  declare module.exports: $Exports<'react-social-icons/lib/social-icons'>;
}
declare module 'react-social-icons/lib/styles.js' {
  declare module.exports: $Exports<'react-social-icons/lib/styles'>;
}
declare module 'react-social-icons/lib/symbols.js' {
  declare module.exports: $Exports<'react-social-icons/lib/symbols'>;
}
