// flow-typed signature: 0385b2de94283bdcf6f0faec08ffd360
// flow-typed version: <<STUB>>/rmwc_v^1.3.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rmwc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rmwc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rmwc/Base/DocumentComponent' {
  declare module.exports: any;
}

declare module 'rmwc/Base/index' {
  declare module.exports: any;
}

declare module 'rmwc/Base/noop' {
  declare module.exports: any;
}

declare module 'rmwc/Base/randomId' {
  declare module.exports: any;
}

declare module 'rmwc/Base/simpleTag' {
  declare module.exports: any;
}

declare module 'rmwc/Base/story-with-state' {
  declare module.exports: any;
}

declare module 'rmwc/Base/testPolyfill' {
  declare module.exports: any;
}

declare module 'rmwc/Base/withMDC' {
  declare module.exports: any;
}

declare module 'rmwc/Base/withMDCToggle' {
  declare module.exports: any;
}

declare module 'rmwc/Base/withRipple' {
  declare module.exports: any;
}

declare module 'rmwc/Base/withTheme' {
  declare module.exports: any;
}

declare module 'rmwc/Button/index' {
  declare module.exports: any;
}

declare module 'rmwc/Card/index' {
  declare module.exports: any;
}

declare module 'rmwc/Checkbox/index' {
  declare module.exports: any;
}

declare module 'rmwc/Chip/index' {
  declare module.exports: any;
}

declare module 'rmwc/config-overrides' {
  declare module.exports: any;
}

declare module 'rmwc/Dialog/index' {
  declare module.exports: any;
}

declare module 'rmwc/Drawer/index' {
  declare module.exports: any;
}

declare module 'rmwc/Elevation/index' {
  declare module.exports: any;
}

declare module 'rmwc/Fab/index' {
  declare module.exports: any;
}

declare module 'rmwc/FormField/index' {
  declare module.exports: any;
}

declare module 'rmwc/Grid/index' {
  declare module.exports: any;
}

declare module 'rmwc/GridList/index' {
  declare module.exports: any;
}

declare module 'rmwc/Icon/index' {
  declare module.exports: any;
}

declare module 'rmwc/IconToggle/index' {
  declare module.exports: any;
}

declare module 'rmwc/lib/rmwc.umd' {
  declare module.exports: any;
}

declare module 'rmwc/LinearProgress/index' {
  declare module.exports: any;
}

declare module 'rmwc/List/index' {
  declare module.exports: any;
}

declare module 'rmwc/Menu/index' {
  declare module.exports: any;
}

declare module 'rmwc/Provider/index' {
  declare module.exports: any;
}

declare module 'rmwc/Radio/index' {
  declare module.exports: any;
}

declare module 'rmwc/Ripple/index' {
  declare module.exports: any;
}

declare module 'rmwc/Select/index' {
  declare module.exports: any;
}

declare module 'rmwc/Slider/index' {
  declare module.exports: any;
}

declare module 'rmwc/Snackbar/index' {
  declare module.exports: any;
}

declare module 'rmwc/Switch/index' {
  declare module.exports: any;
}

declare module 'rmwc/Tabs/index' {
  declare module.exports: any;
}

declare module 'rmwc/TextField/index' {
  declare module.exports: any;
}

declare module 'rmwc/Theme/index' {
  declare module.exports: any;
}

declare module 'rmwc/Theme/theme-options' {
  declare module.exports: any;
}

declare module 'rmwc/Toolbar/index' {
  declare module.exports: any;
}

declare module 'rmwc/Typography/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rmwc/Base/DocumentComponent.js' {
  declare module.exports: $Exports<'rmwc/Base/DocumentComponent'>;
}
declare module 'rmwc/Base/index.js' {
  declare module.exports: $Exports<'rmwc/Base/index'>;
}
declare module 'rmwc/Base/noop.js' {
  declare module.exports: $Exports<'rmwc/Base/noop'>;
}
declare module 'rmwc/Base/randomId.js' {
  declare module.exports: $Exports<'rmwc/Base/randomId'>;
}
declare module 'rmwc/Base/simpleTag.js' {
  declare module.exports: $Exports<'rmwc/Base/simpleTag'>;
}
declare module 'rmwc/Base/story-with-state.js' {
  declare module.exports: $Exports<'rmwc/Base/story-with-state'>;
}
declare module 'rmwc/Base/testPolyfill.js' {
  declare module.exports: $Exports<'rmwc/Base/testPolyfill'>;
}
declare module 'rmwc/Base/withMDC.js' {
  declare module.exports: $Exports<'rmwc/Base/withMDC'>;
}
declare module 'rmwc/Base/withMDCToggle.js' {
  declare module.exports: $Exports<'rmwc/Base/withMDCToggle'>;
}
declare module 'rmwc/Base/withRipple.js' {
  declare module.exports: $Exports<'rmwc/Base/withRipple'>;
}
declare module 'rmwc/Base/withTheme.js' {
  declare module.exports: $Exports<'rmwc/Base/withTheme'>;
}
declare module 'rmwc/Button/index.js' {
  declare module.exports: $Exports<'rmwc/Button/index'>;
}
declare module 'rmwc/Card/index.js' {
  declare module.exports: $Exports<'rmwc/Card/index'>;
}
declare module 'rmwc/Checkbox/index.js' {
  declare module.exports: $Exports<'rmwc/Checkbox/index'>;
}
declare module 'rmwc/Chip/index.js' {
  declare module.exports: $Exports<'rmwc/Chip/index'>;
}
declare module 'rmwc/config-overrides.js' {
  declare module.exports: $Exports<'rmwc/config-overrides'>;
}
declare module 'rmwc/Dialog/index.js' {
  declare module.exports: $Exports<'rmwc/Dialog/index'>;
}
declare module 'rmwc/Drawer/index.js' {
  declare module.exports: $Exports<'rmwc/Drawer/index'>;
}
declare module 'rmwc/Elevation/index.js' {
  declare module.exports: $Exports<'rmwc/Elevation/index'>;
}
declare module 'rmwc/Fab/index.js' {
  declare module.exports: $Exports<'rmwc/Fab/index'>;
}
declare module 'rmwc/FormField/index.js' {
  declare module.exports: $Exports<'rmwc/FormField/index'>;
}
declare module 'rmwc/Grid/index.js' {
  declare module.exports: $Exports<'rmwc/Grid/index'>;
}
declare module 'rmwc/GridList/index.js' {
  declare module.exports: $Exports<'rmwc/GridList/index'>;
}
declare module 'rmwc/Icon/index.js' {
  declare module.exports: $Exports<'rmwc/Icon/index'>;
}
declare module 'rmwc/IconToggle/index.js' {
  declare module.exports: $Exports<'rmwc/IconToggle/index'>;
}
declare module 'rmwc/index' {
  declare module.exports: $Exports<'rmwc'>;
}
declare module 'rmwc/index.js' {
  declare module.exports: $Exports<'rmwc'>;
}
declare module 'rmwc/lib/rmwc.umd.js' {
  declare module.exports: $Exports<'rmwc/lib/rmwc.umd'>;
}
declare module 'rmwc/LinearProgress/index.js' {
  declare module.exports: $Exports<'rmwc/LinearProgress/index'>;
}
declare module 'rmwc/List/index.js' {
  declare module.exports: $Exports<'rmwc/List/index'>;
}
declare module 'rmwc/Menu/index.js' {
  declare module.exports: $Exports<'rmwc/Menu/index'>;
}
declare module 'rmwc/Provider/index.js' {
  declare module.exports: $Exports<'rmwc/Provider/index'>;
}
declare module 'rmwc/Radio/index.js' {
  declare module.exports: $Exports<'rmwc/Radio/index'>;
}
declare module 'rmwc/Ripple/index.js' {
  declare module.exports: $Exports<'rmwc/Ripple/index'>;
}
declare module 'rmwc/Select/index.js' {
  declare module.exports: $Exports<'rmwc/Select/index'>;
}
declare module 'rmwc/Slider/index.js' {
  declare module.exports: $Exports<'rmwc/Slider/index'>;
}
declare module 'rmwc/Snackbar/index.js' {
  declare module.exports: $Exports<'rmwc/Snackbar/index'>;
}
declare module 'rmwc/Switch/index.js' {
  declare module.exports: $Exports<'rmwc/Switch/index'>;
}
declare module 'rmwc/Tabs/index.js' {
  declare module.exports: $Exports<'rmwc/Tabs/index'>;
}
declare module 'rmwc/TextField/index.js' {
  declare module.exports: $Exports<'rmwc/TextField/index'>;
}
declare module 'rmwc/Theme/index.js' {
  declare module.exports: $Exports<'rmwc/Theme/index'>;
}
declare module 'rmwc/Theme/theme-options.js' {
  declare module.exports: $Exports<'rmwc/Theme/theme-options'>;
}
declare module 'rmwc/Toolbar/index.js' {
  declare module.exports: $Exports<'rmwc/Toolbar/index'>;
}
declare module 'rmwc/Typography/index.js' {
  declare module.exports: $Exports<'rmwc/Typography/index'>;
}
