{
  properties {
    id
    location {
      latitude
      longitude
    }
    address
    city
    features
    priority
    isFeatured
    imageBanner
    zoning
    media {
      handle
      isFeatured
      priority
    }
    units {
      id
      price
      bedrooms
      bathrooms
      description
      features
      utilitiesIncluded
      availabilityDate
      media {
        handle
        isFeatured
        priority
      }
    }
  }
}
