{
  allProperties {
    id
    location
    address
    media {
      handle
      isFeatured
    }
    units {
      price
      bedrooms
      bathrooms
      media {
        handle
        isFeatured
      }
    }
  }
}
