{
  allProperties {
    id
    location
    address
    city
    zoning
    features
    priority
    isFeatured
    imageBanner
    media {
      handle
      isFeatured
      priority
    }
    units {
      id
      type
      squareFeet
      price
      bedrooms
      bathrooms
      description
      features
      utilitiesIncluded
      availabilityDate
      prioritizePropertyImages
      media {
        handle
        isFeatured
        priority
      }
    }
  }
}
