query getProperty($id: ID) {
  Property (id: $id) {
    id
    location
    address
    city
    type
    features
    numberOfFloors
    media {
      handle
      isFeatured
      priority
    }
    units {
      id
      price
      bedrooms
      bathrooms
      description
      features
      utilitiesIncluded
      availabilityDate
      virtualTourURL
      media {
        handle
        isFeatured
        priority
      }
    }
  }
}
