// flow-typed signature: c7c6b2fdd71615dec4290c28c4533238
// flow-typed version: <<STUB>>/@ibm/type_v^0.5.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ibm/type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ibm/type' {
  declare module.exports: any;
}
