// flow-typed signature: f505d38335c6c20a41a98f9567f54b48
// flow-typed version: <<STUB>>/@typeform/embed_v^0.5.6/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@typeform/embed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@typeform/embed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@typeform/embed/dist/demo' {
  declare module.exports: any;
}

declare module '@typeform/embed/dist/embed' {
  declare module.exports: any;
}

declare module '@typeform/embed/dist/share' {
  declare module.exports: any;
}

declare module '@typeform/embed/dist/widget' {
  declare module.exports: any;
}

declare module '@typeform/embed/lib/api' {
  declare module.exports: any;
}

// Filename aliases
declare module '@typeform/embed/dist/demo.js' {
  declare module.exports: $Exports<'@typeform/embed/dist/demo'>;
}
declare module '@typeform/embed/dist/embed.js' {
  declare module.exports: $Exports<'@typeform/embed/dist/embed'>;
}
declare module '@typeform/embed/dist/share.js' {
  declare module.exports: $Exports<'@typeform/embed/dist/share'>;
}
declare module '@typeform/embed/dist/widget.js' {
  declare module.exports: $Exports<'@typeform/embed/dist/widget'>;
}
declare module '@typeform/embed/lib/api.js' {
  declare module.exports: $Exports<'@typeform/embed/lib/api'>;
}
